#!/bin/bash

/usr/bin/ansible proxy,webservers,database -b -m user -a "name=automation"
/usr/bin/ansible proxy,webservers,database -b -m file -a "path=/home/automation/.ssh  state=directory owner=automation"
/usr/bin/ansible proxy,webservers,database -b -m copy -a "src=/home/automation/.ssh/id_rsa.pub  dest=/home/automation/.ssh/authorized_keys directory_mode=yes"
/usr/bin/ansible proxy,webservers,database -b -m lineinfile -a "path=/etc/sudoers state=present line='automation ALL=(ALL) NOPASSWD: ALL'"
