---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  
  - name: Packages for proxy
    yum:
      name:
        - tcpdump
        - mailx
      state: present
    when: inventory_hostname in groups['proxy']
    tags: proxy

  - name: Packages for database
    yum:
      name:
      - lsof
      - mailx
      state: present
    when: inventory_hostname in groups['database']
    tags: database

