---
# tasks file for sample-mysql

- name: Installing packages
  yum:
    name:
    - parted
    - python
    - MySQL-python
    - firewalld
    - mysql-community-server
    state: present
  tags: install

#- name: Create a new primary partition for LVM
#  parted:
#    device: /dev/sdb
#    number: 1
#    flags: [ lvm ]
#    state: present
#    part_end: 800MiB        
#  register: device_info

# Maybe lvg is not needed, maybe we can use lvol instead to creaate both vg and lv
#- name: create logical volume group
#  lvg:
#    vg: vg_database
#    pvs: /dev/sdb1 

# - name: create logical volume
#     lvol:
#       vg: vg_database
#       lv: lv_mysql
#       pvs: /dev/sdb1
#       size: 512m

# - name: Create a ext2 filesystem on /dev/sdb1
#   filesystem:
#     fstype: xfs
#     dev: lv_mysql
          
# - name: Mount file system
#   mount:
#     path: /mnt/mysql_backups
#     src: lv_mysql
#     fstype: xfs
#     state: present
                      
          
- name: Starting services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - firewalld
  - mysql


- name: Open ports on firewall
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled


- name: Adding root user to MySql
  mysql_user:
    name: root
    password: "{{ database_password }}"


- name: Adding template to my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - RestartMySql


# The handlers will run when forced even if there's a failure..
# # However in this case, there is no failure, what's happening is there is no notification to that handler..
# # Without a notification, handlers won't run even if force_handlers is set.
# # We need changed_when : true to force handlers even if firewalld or mysql are already installed
#
#- name: install firewalld
##  yum:
##    name: firewalld
##    state: present
##  changed_when: true
##  notify:
##  - firewalld1
##  - firewalld2
#
