---
# tasks file for sample-mysql

# The handlers will run when forced even if there's a failure..
# However in this case, there is no failure, what's happening is there is no notification to that handler..
# Without a notification, handlers won't run even if force_handlers is set.
# We need changed_when : true to force handlers even if firewalld or mysql are already installed      


#- name: install parted
#  yum:
#    name: parted
#    state: present

#- name: Create a new primary partition for LVM
#  parted:
#    device: /dev/sdb
#    number: 1
#    flags: [ lvm ]
#    state: present
#    part_end: 800MiB        
#  register: device_info

# Maybe lvg is not needed, maybe we can use lvol instead to creaate both vg and lv
#- name: create logical volume group
#  lvg:
#    vg: vg_database
#    pvs: /dev/sdb1 

# - name: create logical volume
#     lvol:
#       vg: vg_database
#       lv: lv_mysql
#       pvs: /dev/sdb1
#       size: 512m

# - name: Create a ext2 filesystem on /dev/sdb1
#   filesystem:
#     fstype: xfs
#     dev: lv_mysql
          
# - name: Mount file system
#   mount:
#     path: /mnt/mysql_backups
#     src: lv_mysql
#     fstype: xfs
#     state: present
                      
          
- name: install firewalld
  yum:
    name: firewalld
    state: present
  changed_when: true
  notify:  
  - firewalld1
  - firewalld2
    
- name: install mysql
  yum:
    name: mysql-community-server
    state: present
  changed_when: true
  notify:
  - mysql1
  - mysql2

- name: template
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: install python
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - python
  - MySQL-python
  